### ISSUE TITLE
Not counting in Hacktoberfest

### ISSUE THREAD

**Issue by Ace117MC** [mauryahimanshu/Must-know-Algorithms-for-competitive-coding#10]
PR is not counted in Hacktoberfest
It is maybe due to capital H in Hacktoberfest
Maybe changing it to hacktoberfest will help

**Comment by mauryahimanshu** [comment]
I don't think that's the problem. I have updated the repo details. Please wait for some time to capture all PRs.

**Comment by Prashuk156** [comment]
The Hacktoberfest website shows this
In Review
Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.

**Comment by mauryahimanshu** [comment]
Yes it is absolutely normal.
